=== fildpauz/adaps/docs/xml/adaps.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/adaps.dtd.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE document SYSTEM "adaps.dtd.dtd">

    <document>
    ...
    </document>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT document (title,citation,url,info?,body)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT citation (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT url (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT info (arise-info)?>
<!ATTLIST info
    type (arise|science-news|other) #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT arise-info EMPTY>
<!ATTLIST arise-info
    book CDATA #REQUIRED
    section CDATA #IMPLIED
    unit CDATA #IMPLIED
    part CDATA #IMPLIED
    item CDATA #IMPLIED
    firstpage CDATA #REQUIRED
    lastpage CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT body (paragraph)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT paragraph (sentence)*>
<!ATTLIST paragraph
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sentence (t|punc|abbr|anaphor|emph|connector|sentence|term)*>
<!ATTLIST sentence
    par-function CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT t (#PCDATA)>
<!ATTLIST t
    id CDATA #IMPLIED
    type CDATA #IMPLIED
    parts CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT punc (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT abbr (t)*>
<!ATTLIST abbr
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT anaphor (t|punc)*>
<!ATTLIST anaphor
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT emph (t|punc|abbr|anaphor|term)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT connector (t|anaphor)*>
<!ATTLIST connector
    id CDATA #IMPLIED
    type CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT term (t|punc)*>
<!ATTLIST term
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

=== fildpauz/adaps/docs/pipeline/4-annotate/in/fracture-geology.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Fracture (geology)</title>
    <citation>Wikipedia contributors, “Fracture (geology),” Wikipedia, The Free Encyclopedia, Retrieved from https://simple.wikipedia.org/w/index.php?title=Fracture_(geology)&amp;oldid=4708627 (accessed on January 22, 2017)</citation>
    <url>https://simple.wikipedia.org/w/index.php?title=Fracture_(geology)&amp;oldid=4708627</url>
    <info type="wikipedia"/>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01" type="GSL-1">In</t>
                <t id="p01-s01-t02">geology</t>
                <punc>,</punc>
                <term>
                    <t id="p01-s01-t03" type="GSL-1">a</t>
                    <t id="p01-s01-t04">fracture</t>
                </term>
                <t id="p01-s01-t05" type="GSL-1">is</t>
                <t id="p01-s01-t06" type="GSL-1">any</t>
                <t id="p01-s01-t07" type="GSL-1">kind</t>
                <t id="p01-s01-t08" type="GSL-1">of</t>
                <t id="p01-s01-t09" type="GSL-1">separation</t>
                <t id="p01-s01-t10" type="GSL-1">or</t>
                <t id="p01-s01-t11" type="GSL-1">break</t>
                <t id="p01-s01-t12" type="GSL-1">in</t>
                <t id="p01-s01-t13" type="GSL-1">a</t>
                <t id="p01-s01-t14" type="GSL-1">rock</t>
                <t id="p01-s01-t15" type="GSL-1">formation</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s02">
                <t id="p01-s02-t01" type="GSL-1">Examples</t>
                <t id="p01-s02-t02" type="GSL-1">are</t>
                <t id="p01-s02-t03" type="GSL-1">joints</t>
                <t id="p01-s02-t04" type="GSL-1">or</t>
                <t id="p01-s02-t05" type="GSL-2">faults</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s03">
                <anaphor>
                    <t id="p01-s03-t01" type="GSL-1">These</t>
                </anaphor>
                <t id="p01-s03-t02" type="GSL-1">divides</t>
                <anaphor>
                    <t id="p01-s03-t03" type="GSL-1">the</t>
                    <t id="p01-s03-t04" type="GSL-1">rock</t>
                </anaphor>
                <t id="p01-s03-t05" type="GSL-1">into</t>
                <t id="p01-s03-t06" type="GSL-1">two</t>
                <t id="p01-s03-t07" type="GSL-1">or</t>
                <t id="p01-s03-t08" type="GSL-1">more</t>
                <t id="p01-s03-t09" type="GSL-1">pieces</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s04">
                <t id="p01-s04-t01" type="GSL-1">A</t>
                <t id="p01-s04-t02">fracture</t>
                <t id="p01-s04-t03" type="GSL-1">can</t>
                <t id="p01-s04-t04" type="GSL-1">sometimes</t>
                <t id="p01-s04-t05" type="GSL-1">form</t>
                <t id="p01-s04-t06" type="GSL-1">a</t>
                <t id="p01-s04-t07" type="GSL-1">deep</t>
                <punc>,</punc>
                <t id="p01-s04-t08" type="GSL-1">wide</t>
                <t id="p01-s04-t09" type="GSL-2">crack</t>
                <t id="p01-s04-t10" type="GSL-1">in</t>
                <anaphor>
                    <t id="p01-s04-t11" type="GSL-1">the</t>
                    <t id="p01-s04-t12" type="GSL-1">rock</t>
                </anaphor>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s05">
                <anaphor>
                    <t id="p01-s05-t01" type="GSL-1">They</t>
                </anaphor>
                <t id="p01-s05-t02" type="GSL-1">are</t>
                <t id="p01-s05-t03" type="GSL-1">usually</t>
                <t id="p01-s05-t04" type="GSL-1">caused</t>
                <connector>
                    <t id="p01-s05-t05" type="GSL-1">when</t>
                </connector>
                <anaphor>
                    <t id="p01-s05-t06" type="GSL-1">the</t>
                    <t id="p01-s05-t07" type="GSL-1">rock</t>
                </anaphor>
                <t id="p01-s05-t08" type="GSL-1">is</t>
                <t id="p01-s05-t09" type="GSL-1">not</t>
                <t id="p01-s05-t10" type="GSL-1">strong</t>
                <t id="p01-s05-t11" type="GSL-1">enough</t>
                <t id="p01-s05-t12" type="GSL-1">to</t>
                <t id="p01-s05-t13" type="GSL-1">hold</t>
                <t id="p01-s05-t14" type="GSL-1">up</t>
                <t id="p01-s05-t15" type="GSL-1">under</t>
                <t id="p01-s05-t16" type="GSL-1">too</t>
                <t id="p01-s05-t17" type="GSL-1">much</t>
                <t id="p01-s05-t18" type="Coxhead-AWL-4,AR-AWL-4b">stress</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s06">
                <anaphor>
                    <t id="p01-s06-t01" type="GSL-1">This</t>
                </anaphor>
                <t id="p01-s06-t02" type="GSL-1">makes</t>
                <anaphor>
                    <t id="p01-s06-t03" type="GSL-1">the</t>
                    <t id="p01-s06-t04" type="GSL-1">rock</t>
                </anaphor>
                <t id="p01-s06-t05" type="GSL-2">crack</t>
                <t id="p01-s06-t06" type="GSL-1">along</t>
                <anaphor>
                    <t id="p01-s06-t07" type="GSL-1">its</t>
                </anaphor>
                <t id="p01-s06-t08">weakest</t>
                <t id="p01-s06-t09" type="GSL-1">point</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s07">
                <t id="p01-s07-t01">Fractures</t>
                <t id="p01-s07-t02" type="GSL-1">can</t>
                <t id="p01-s07-t03" type="GSL-1">provide</t>
                <t id="p01-s07-t04" type="Coxhead-AWL-4,AR-AWL-4a">access</t>
                <t id="p01-s07-t05" type="GSL-1">for</t>
                <t id="p01-s07-t06">fluids</t>
                <punc>,</punc>
                <t id="p01-s07-t07" type="GSL-1">like</t>
                <t id="p01-s07-t08" type="GSL-1">water</t>
                <t id="p01-s07-t09" type="GSL-1">or</t>
                <t id="p01-s07-t10">hydrocarbons</t>
                <punc>,</punc>
                <t id="p01-s07-t11" type="GSL-1">to</t>
                <t id="p01-s07-t12" type="GSL-1">move</t>
                <t id="p01-s07-t13" type="GSL-1">into</t>
                <anaphor>
                    <t id="p01-s07-t14" type="GSL-1">the</t>
                    <t id="p01-s07-t15" type="GSL-1">rock</t>
                </anaphor>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/3-classify-words/in/crows.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Extract from Modifications to the Aesop's Fable Paradigm Change New Caledonian Crow Performances</title>
    <citation> Logan CJ, Jelbert SA, Breen AJ, Gray RD, Taylor AH (2014) Modifications to the Aesop's Fable Paradigm Change New Caledonian Crow Performances. PLoS ONE 9(7): e103049. doi:10.1371/journal.pone.0103049 
        Retrieved from http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0103049 on 07 Dec 2016</citation>
    <url>http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0103049</url>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01">While</t>
                <t id="p01-s01-t02">previous</t>
                <t id="p01-s01-t03">work</t>
                <t id="p01-s01-t04">has</t>
                <t id="p01-s01-t05">suggested</t>
                <t id="p01-s01-t06">that</t>
                <t id="p01-s01-t07">New</t>
                <t id="p01-s01-t08">Caledonian</t>
                <t id="p01-s01-t09">crows</t>
                <punc>[</punc>
                <t id="p01-s01-t10">13</t>
                <punc>]</punc>
                <punc>,</punc>
                <t id="p01-s01-t11">like</t>
                <t id="p01-s01-t12">Eurasian</t>
                <t id="p01-s01-t13">jays</t>
                <punc>[</punc>
                <t id="p01-s01-t14">18</t>
                <punc>]</punc>
                <punc>,</punc>
                <t id="p01-s01-t15">and</t>
                <t id="p01-s01-t16">children</t>
                <t id="p01-s01-t17">under</t>
                <t id="p01-s01-t18">7</t>
                <t id="p01-s01-t19">years</t>
                <t id="p01-s01-t20">of</t>
                <t id="p01-s01-t21">age</t>
                <punc>[</punc>
                <t id="p01-s01-t22">16</t>
                <punc>]</punc>
                <punc>,</punc>
                <t id="p01-s01-t23">cannot</t>
                <t id="p01-s01-t24">solve</t>
                <t id="p01-s01-t25">the</t>
                <t id="p01-s01-t26">U</t>
				<punc>-</punc>
				<t id="p01-s01-t27">tube</t>
                <t id="p01-s01-t28">task</t>
                <punc>,</punc>
                <t id="p01-s01-t29">here</t>
                <t id="p01-s01-t30">one</t>
                <t id="p01-s01-t31">crow</t>
                <punc>,</punc>
                <t id="p01-s01-t32">Kitty</t>
                <punc>,</punc>
                <t id="p01-s01-t33">was</t>
                <t id="p01-s01-t34">able</t>
                <t id="p01-s01-t35">to</t>
                <t id="p01-s01-t36">do</t>
                <t id="p01-s01-t37">so</t>
                <t id="p01-s01-t38">by</t>
                <t id="p01-s01-t39">learning</t>
                <t id="p01-s01-t40">the</t>
                <t id="p01-s01-t41">connection</t>
                <t id="p01-s01-t42">between</t>
                <t id="p01-s01-t43">the</t>
                <t id="p01-s01-t44">arbitrary</t>
                <t id="p01-s01-t45">color</t>
                <t id="p01-s01-t46">cue</t>
                <t id="p01-s01-t47">and</t>
                <t id="p01-s01-t48">the</t>
                <t id="p01-s01-t49">movement</t>
                <t id="p01-s01-t50">of</t>
                <t id="p01-s01-t51">the</t>
                <t id="p01-s01-t52">food</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/4-annotate/in/cause-and-effect-connectors-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>1st century BC (Extract)</title>
    <citation>Simple English Wikipedia: “1st century BC”. Retrieved from https://simple.wikipedia.org/wiki/1st_century_BC on 20 Aug 2015.</citation>
    <url>https://simple.wikipedia.org/wiki/1st_century_BC</url>
    <info type="arise">
        <arise-info book="2"
                    section="2"
                    unit="2"
                    part="4"
                    item="0"
                    firstpage="19"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01" type="GSL-1">The</t>
                <t id="p01-s01-t02">1st</t>
                    <t id="p01-s01-t03" type="GSL-2">century</t>
                <t id="p01-s01-t04">BC</t>
                <t id="p01-s01-t05" type="GSL-1">started</t>
                <t id="p01-s01-t06" type="GSL-1">on</t>
                <t id="p01-s01-t07" type="GSL-1">January</t>
                <t id="p01-s01-t08">1</t>
                <punc>,</punc>
                <t id="p01-s01-t09">100</t>
                <t id="p01-s01-t10">BC</t>
                <t id="p01-s01-t11" type="GSL-1">and</t>
                <t id="p01-s01-t12" type="GSL-1">ended</t>
                <t id="p01-s01-t13" type="GSL-1">on</t>
                <t id="p01-s01-t14" type="GSL-1">December</t>
                <t id="p01-s01-t15">31</t>
                <punc>,</punc>
                <t id="p01-s01-t16">1</t>
                <t id="p01-s01-t17">BC</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s02">
                <t id="p01-s02-t01" type="GSL-1">An</t>
                <t id="p01-s02-t02" type="Coxhead-AWL-3,AR-AWL-3a">alternative</t>
                <t id="p01-s02-t03" type="GSL-1">name</t>
                <t id="p01-s02-t04" type="GSL-1">for</t>
                <anaphor>
                    <t id="p01-s02-t05" type="GSL-1">this</t>
                    <t id="p01-s02-t06" type="GSL-2">century</t>
                </anaphor>
                <t id="p01-s02-t07" type="GSL-1">is</t>
                <t id="p01-s02-t08" type="GSL-1">the</t>
                <t id="p01-s02-t09" type="GSL-1">last</t>
                <t id="p01-s02-t10" type="GSL-2">century</t>
                <t id="p01-s02-t11">BC</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s03">
                <t id="p01-s03-t01" type="GSL-1">The</t>
                <t id="p01-s03-t02">AD/BC</t>
                <t id="p01-s03-t03">notation</t>
                <t id="p01-s03-t04" type="GSL-1">does</t>
                <t id="p01-s03-t05" type="GSL-1">not</t>
                <t id="p01-s03-t06" type="GSL-1">use</t>
                <t id="p01-s03-t07" type="GSL-1">a</t>
                <t id="p01-s03-t08" type="GSL-1">year</t>
                <t id="p01-s03-t09" type="GSL-2">zero</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s04">
                <t id="p01-s04-t01" type="GSL-1">Scientific</t>
                <t id="p01-s04-t02">notation</t>
                <t id="p01-s04-t03" type="GSL-1">does</t>
                <punc>,</punc>
                <connector>
                    <t id="p01-s04-t04" type="GSL-1">however</t>
                </connector>
                <t id="p01-s04-t05" type="GSL-1">use</t>
                <t id="p01-s04-t06" type="GSL-1">a</t>
                <t id="p01-s04-t07">minus</t>
                <t id="p01-s04-t08" type="GSL-1">sign</t>
                <punc>,</punc>
                <t id="p01-s04-t09" type="GSL-1">so</t>
                <punc>&#8216;</punc>
                <t id="p01-s04-t10">2</t>
                <t id="p01-s04-t11">BC</t>
                <punc>&#8217;</punc>
                <t id="p01-s04-t12" type="GSL-1">is</t>
                <t id="p01-s04-t13" type="GSL-1">equal</t>
                <t id="p01-s04-t14" type="GSL-1">to</t>
                <punc>&#8216;</punc>
                <t id="p01-s04-t15" type="GSL-1">year</t>
                <t id="p01-s04-t16">−1</t>
                <punc>&#8217;</punc>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/1-tokenize/out/resemblance-connectors-8.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Water (Extract)</title>
    <citation>Simple English Wikipedia: “Food group”. Retrieved from https://simple.wikipedia.org/wiki/Food_group on 20 Aug 2015.</citation>
    <url>https://simple.wikipedia.org/wiki/Food_group</url>
    <info type="arise">
        <arise-info book="2" section="2" unit="1" part="4" item="7" firstpage="16"/>
    </info>
    <body>
        <paragraph>
            <sentence>
                <t>Water</t>
                <t>is</t>
                <t>treated</t>
                <t>in</t>
                <t>very</t>
                <t>different</t>
                <t>ways</t>
                <t>by</t>
                <t>different</t>
                <t>nutrition</t>
                <t>guides</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>Some</t>
                <t>nutrition</t>
                <t>guides</t>
                <t>do</t>
                <t>not</t>
                <t>include</t>
                <t>water</t>
                <punc>,</punc>
                <t>while</t>
                <t>others</t>
                <t>include</t>
                <t>it</t>
                <punc>,</punc>
                <t>and</t>
                <t>yet</t>
                <t>others</t>
                <t>make</t>
                <t>it</t>
                <t>the</t>
                <t>most</t>
                <t>important</t>
                <t>part</t>
                <t>or</t>
                <t>basic</t>
                <t>part</t>
                <t>of</t>
                <t>the</t>
                <t>guide</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <punc>[</punc>
                <punc>“</punc>
                <t>Food</t>
                <t>group</t>
                <punc>”</punc>
                <punc>]</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/4-annotate/in/resemblance-connectors-6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Edubuntu (Extract)</title>
    <citation>Simple English Wikipedia: “Edubuntu”. Retrieved from https://simple.wikipedia.org/wiki/Edubuntu on 24 Aug 2015.</citation>
    <url>https://simple.wikipedia.org/wiki/Edubuntu</url>
    <info type="arise">
        <arise-info book="2"
                    section="2"
                    unit="1"
                    part="4"
                    item="5"
                    firstpage="16"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01" type="GSL-1">The</t>
                <t id="p01-s01-t02" type="Coxhead-AWL-4,AR-AWL-4b">principal</t>
                <t id="p01-s01-t03" type="Coxhead-AWL-2,AR-AWL-2a">design</t>
                <t id="p01-s01-t04" type="Coxhead-AWL-4,AR-AWL-4a">goals</t>
                <t id="p01-s01-t05" type="GSL-1">of</t>
                <t id="p01-s01-t06">Edubuntu</t>
                <t id="p01-s01-t07" type="GSL-1">are</t>
                <t id="p01-s01-t08" type="GSL-1">easier</t>
                <t id="p01-s01-t09">configuration</t>
                <punc>,</punc>
                <t id="p01-s01-t10" type="GSL-1">users</t>
                <t id="p01-s01-t11" type="GSL-1">and</t>
                <t id="p01-s01-t12" type="Coxhead-AWL-1,AR-AWL-1b">processes</t>
                <punc>,</punc>
                <t id="p01-s01-t13" type="GSL-1">together</t>
                <t id="p01-s01-t14" type="GSL-1">with</t>
                <t id="p01-s01-t15" type="GSL-1">ways</t>
                <t id="p01-s01-t16" type="GSL-1">for</t>
                <t id="p01-s01-t17" type="GSL-1">working</t>
                <t id="p01-s01-t18" type="GSL-1">together</t>
                <t id="p01-s01-t19" type="GSL-1">in</t>
                <t id="p01-s01-t20">classrooms</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s02">
                <connector>
                    <t id="p01-s02-t01" type="GSL-1">Equally</t>
                </connector>
                <t id="p01-s02-t02" type="GSL-1">important</t>
                <t id="p01-s02-t03" type="GSL-1">is</t>
                <t id="p01-s02-t04" type="GSL-1">the</t>
                <t id="p01-s02-t05" type="GSL-1">gathering</t>
                <t id="p01-s02-t06" type="GSL-1">together</t>
                <t id="p01-s02-t07" type="GSL-1">of</t>
                <t id="p01-s02-t08" type="GSL-1">the</t>
                <t id="p01-s02-t09" type="GSL-1">best</t>
                <t id="p01-s02-t10" type="Coxhead-AWL-1,AR-AWL-1a">available</t>
                <t id="p01-s02-t11" type="GSL-1">free</t>
                <t id="p01-s02-t12">software</t>
                <t id="p01-s02-t13" type="GSL-1">and</t>
                <t id="p01-s02-t14">digital</t>
                <t id="p01-s02-t15" type="GSL-1">materials</t>
                <t id="p01-s02-t16" type="GSL-1">for</t>
                <t id="p01-s02-t17" type="GSL-2">education</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/2-attach-ids/in/cause-and-effect-connectors-6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Edwin Hubble (Extract)</title>
    <citation>Simple English Wikipedia: “Edwin Hubble”. Retrieved from https://simple.wikipedia.org/wiki/Edwin_Hubble on 20 Aug 2015.</citation>
    <url>https://simple.wikipedia.org/wiki/Edwin_Hubble</url>
    <info type="arise">
        <arise-info book="2"
                    section="2"
                    unit="2"
                    part="4"
                    item="5"
                    firstpage="20"/>
    </info>
    <body>
        <paragraph>
            <sentence>
                <t>In</t>
                <t>1929</t>
                <t>Hubble</t>
                <t>formulated</t>
                <t>what</t>
                <t>is</t>
                <t>called</t>
                <t>Hubble's</t>
                <t>law</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>The</t>
                <t>law</t>
                <t>states</t>
                <t>that</t>
                <t>the</t>
                <t>greater</t>
                <t>the</t>
                <t>distance</t>
                <t>between</t>
                <t>any</t>
                <t>two</t>
                <t>galaxies</t>
                <punc>,</punc>
                <t>the</t>
                <t>greater</t>
                <t>their</t>
                <t>relative</t>
                <t>speed</t>
                <t>of</t>
                <t>separation</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>Georges</t>
                <t>Lemaître</t>
                <punc>,</punc>
                <t>a</t>
                <t>Belgian</t>
                <t>priest</t>
                <t>and</t>
                <t>astronomer</t>
                <punc>,</punc>
                <t>had</t>
                <t>published</t>
                <t>the</t>
                <t>idea</t>
                <t>two</t>
                <t>years</t>
                <t>before</t>
                <t>in</t>
                <t>an</t>
                <t>obscure</t>
                <t>journal</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>Nevertheless</t>
                <punc>,</punc>
                <t>the</t>
                <t>idea</t>
                <t>bears</t>
                <t>Hubble's</t>
                <t>name</t>
                <t>to</t>
                <t>this</t>
                <t>day</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>
