=== fildpauz/adaps/docs/xml/adaps.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/adaps.dtd.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE document SYSTEM "adaps.dtd.dtd">

    <document>
    ...
    </document>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT document (title,citation,url,info?,body)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT citation (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT url (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT info (arise-info)?>
<!ATTLIST info
    type (arise|science-news|other) #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT arise-info EMPTY>
<!ATTLIST arise-info
    book CDATA #REQUIRED
    section CDATA #IMPLIED
    unit CDATA #IMPLIED
    part CDATA #IMPLIED
    item CDATA #IMPLIED
    firstpage CDATA #REQUIRED
    lastpage CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT body (paragraph)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT paragraph (sentence)*>
<!ATTLIST paragraph
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sentence (t|punc|abbr|anaphor|emph|connector|sentence|term)*>
<!ATTLIST sentence
    par-function CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT t (#PCDATA)>
<!ATTLIST t
    id CDATA #IMPLIED
    type CDATA #IMPLIED
    parts CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT punc (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT abbr (t)*>
<!ATTLIST abbr
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT anaphor (t|punc)*>
<!ATTLIST anaphor
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT emph (t|punc|abbr|anaphor|term)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT connector (t|anaphor)*>
<!ATTLIST connector
    id CDATA #IMPLIED
    type CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT term (t|punc)*>
<!ATTLIST term
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

=== fildpauz/adaps/docs/pipeline/3-classify-words/in/paraphrasing-and-quoting-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Identifiable Images of Bystanders Extracted from Corneal Reflections (Extract)</title>
    <citation>Jenkins R, Kerr C (2013) Identifiable Images of Bystanders Extracted from Corneal Reflections. PLoS ONE 8(12): e83325. doi:10.1371/journal.pone.0083325</citation>
    <url>http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0083325</url>
    <info type="arise">
        <arise-info book="1"
                    section="3"
                    unit="5"
                    part="1"
                    item="A"
                    firstpage="46"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01">By</t>
                <t id="p01-s01-t02">zooming</t>
                <t id="p01-s01-t03">in</t>
                <t id="p01-s01-t04">on</t>
                <t id="p01-s01-t05">high</t>
                <punc>-</punc>
                <t id="p01-s01-t06">resolution</t>
                <t id="p01-s01-t07">passport-style</t>
                <t id="p01-s01-t08">photographs</t>
                <punc>,</punc>
                <t id="p01-s01-t09">we</t>
                <t id="p01-s01-t10">were</t>
                <t id="p01-s01-t11">able</t>
                <t id="p01-s01-t12">to</t>
                <t id="p01-s01-t13">recover</t>
                <t id="p01-s01-t14">images</t>
                <t id="p01-s01-t15">of</t>
                <t id="p01-s01-t16">bystanders</t>
                <t id="p01-s01-t17">from</t>
                <t id="p01-s01-t18">reflections</t>
                <t id="p01-s01-t19">in</t>
                <t id="p01-s01-t20">the</t>
                <t id="p01-s01-t21">eyes</t>
                <t id="p01-s01-t22">of</t>
                <t id="p01-s01-t23">photographic</t>
                <t id="p01-s01-t24">subjects</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s02">
                <t id="p01-s02-t01">Performance</t>
                <t id="p01-s02-t02">in</t>
                <t id="p01-s02-t03">the</t>
                <t id="p01-s02-t04">face</t>
                <t id="p01-s02-t05">matching</t>
                <t id="p01-s02-t06">task</t>
                <punc>(</punc>
                <t id="p01-s02-t07">Experiment</t>
                <t id="p01-s02-t08">1</t>
                <punc>)</punc>
                <t id="p01-s02-t09">and</t>
                <t id="p01-s02-t10">the</t>
                <t id="p01-s02-t11">spontaneous</t>
                <t id="p01-s02-t12">recognition</t>
                <t id="p01-s02-t13">task</t>
                <punc>(</punc>
                <t id="p01-s02-t14">Experiment</t>
                <t id="p01-s02-t15">2</t>
                <punc>)</punc>
                <t id="p01-s02-t16">indicate</t>
                <t id="p01-s02-t17">that</t>
                <t id="p01-s02-t18">these</t>
                <t id="p01-s02-t19">bystander</t>
                <t id="p01-s02-t20">images</t>
                <t id="p01-s02-t21">were</t>
                <t id="p01-s02-t22">not</t>
                <t id="p01-s02-t23">merely</t>
                <t id="p01-s02-t24">informative</t>
                <t id="p01-s02-t25">about</t>
                <t id="p01-s02-t26">facial</t>
                <t id="p01-s02-t27">appearance</t>
                <punc>,</punc>
                <t id="p01-s02-t28">they</t>
                <t id="p01-s02-t29">were</t>
                <t id="p01-s02-t30">properly</t>
                <t id="p01-s02-t31">identifiable</t>
                <t id="p01-s02-t32">to</t>
                <t id="p01-s02-t33">viewers</t>
                <t id="p01-s02-t34">who</t>
                <t id="p01-s02-t35">knew</t>
                <t id="p01-s02-t36">the</t>
                <t id="p01-s02-t37">faces</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s03">
                <t id="p01-s03-t01">This</t>
                <t id="p01-s03-t02">is</t>
                <t id="p01-s03-t03">perhaps</t>
                <t id="p01-s03-t04">a</t>
                <t id="p01-s03-t05">surprising</t>
                <t id="p01-s03-t06">result</t>
                <punc>,</punc>
                <t id="p01-s03-t07">given</t>
                <t id="p01-s03-t08">the</t>
                <t id="p01-s03-t09">very</t>
                <t id="p01-s03-t10">unpromising</t>
                <t id="p01-s03-t11">source</t>
                <t id="p01-s03-t12">of</t>
                <t id="p01-s03-t13">these</t>
                <t id="p01-s03-t14">images</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s04">
                <t id="p01-s04-t01">However</t>
                <punc>,</punc>
                <t id="p01-s04-t02">it</t>
                <t id="p01-s04-t03">is</t>
                <t id="p01-s04-t04">consistent</t>
                <t id="p01-s04-t05">with</t>
                <t id="p01-s04-t06">previous</t>
                <t id="p01-s04-t07">evidence</t>
                <t id="p01-s04-t08">that</t>
                <t id="p01-s04-t09">familiar</t>
                <t id="p01-s04-t10">face</t>
                <t id="p01-s04-t11">recognition</t>
                <t id="p01-s04-t12">is</t>
                <t id="p01-s04-t13">extremely</t>
                <t id="p01-s04-t14">tolerant</t>
                <t id="p01-s04-t15">of</t>
                <t id="p01-s04-t16">poor</t>
                <t id="p01-s04-t17">image</t>
                <t id="p01-s04-t18">quality</t>
                <punc>[</punc>
                <t id="p01-s04-t19">16</t>
                <punc>]</punc>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/2-attach-ids/out/paraphrasing-and-quoting-5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Civil Engineering (Extract)</title>
    <citation>Simple English Wikipedia: “Civil Engineering”. Retrieved from http://simple.wikipedia.org/wiki/Civil_engineering on 19 Feb 2015.</citation>
    <url>http://simple.wikipedia.org/wiki/Civil_engineering</url>
    <info type="arise">
        <arise-info book="1"
                    section="3"
                    unit="5"
                    part="4"
                    item="3"
                    firstpage="48"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01">Civil</t>
                <t id="p01-s01-t02">engineering</t>
                <t id="p01-s01-t03">is</t>
                <t id="p01-s01-t04">made</t>
                <t id="p01-s01-t05">up</t>
                <t id="p01-s01-t06">of</t>
                <t id="p01-s01-t07">many</t>
                <t id="p01-s01-t08">different</t>
                <t id="p01-s01-t09">areas</t>
                <t id="p01-s01-t10">or</t>
                <t id="p01-s01-t11">disciplines</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s02">
                <t id="p01-s02-t01">Some</t>
                <t id="p01-s02-t02">important</t>
                <t id="p01-s02-t03">areas</t>
                <t id="p01-s02-t04">are</t>
                <t id="p01-s02-t05">geotechnical</t>
                <punc>,</punc>
                <t id="p01-s02-t06">structures</t>
                <punc>,</punc>
                <t id="p01-s02-t07">environmental</t>
                <punc>,</punc>
                <t id="p01-s02-t08">construction</t>
                <t id="p01-s02-t09">management</t>
                <punc>,</punc>
                <t id="p01-s02-t10">hydrology</t>
                <punc>,</punc>
                <t id="p01-s02-t11">transportation</t>
                <punc>,</punc>
                <t id="p01-s02-t12">and</t>
                <t id="p01-s02-t13">materials</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s03">
                <t id="p01-s03-t01">It</t>
                <t id="p01-s03-t02">is</t>
                <t id="p01-s03-t03">important</t>
                <t id="p01-s03-t04">for</t>
                <t id="p01-s03-t05">civil</t>
                <t id="p01-s03-t06">engineers</t>
                <t id="p01-s03-t07">to</t>
                <t id="p01-s03-t08">have</t>
                <t id="p01-s03-t09">an</t>
                <t id="p01-s03-t10">understanding</t>
                <t id="p01-s03-t11">of</t>
                <t id="p01-s03-t12">all</t>
                <t id="p01-s03-t13">these</t>
                <t id="p01-s03-t14">disciplines</t>
                <t id="p01-s03-t15">as</t>
                <t id="p01-s03-t16">projects</t>
                <t id="p01-s03-t17">often</t>
                <t id="p01-s03-t18">involve</t>
                <t id="p01-s03-t19">many</t>
                <t id="p01-s03-t20">of</t>
                <t id="p01-s03-t21">them</t>
                <t id="p01-s03-t22">at</t>
                <t id="p01-s03-t23">the</t>
                <t id="p01-s03-t24">same</t>
                <t id="p01-s03-t25">time</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/2-attach-ids/in/fashion.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Extract from The Science of Style: In Fashion, Colors Should Match Only Moderately</title>
    <citation>Gray K, Schmitt P, Strohminger N, Kassam KS (2014) The Science of Style: In Fashion, Colors Should Match Only Moderately. PLoS ONE 9(7): e102772. doi:10.1371/journal.pone.0102772
        Retrieved from http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0102772 on 15 Dec 2016.</citation>
    <url>http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0102772</url>
    <info type="arise">
        <arise-info book="2" section="2" unit="6" part="2" item="C" firstpage="29"/>
    </info>
    <body>
        <paragraph>
            <sentence>
                <t>In</t>
                <t>terms</t>
                <t>of</t>
                <t>fashion</t>
                <punc>,</punc>
                <t>there</t>
                <t>are</t>
                <t>two</t>
                <t>popular</t>
                <t>approaches</t>
                <t>to</t>
                <t>style</t>
                <t>that</t>
                <t>represent</t>
                <punc>“</punc>
                <t>extremes</t>
                <punc>.</punc>
                <punc>”</punc>
            </sentence>
            <sentence>
                <t>On</t>
                <t>one</t>
                <t>hand</t>
                <punc>,</punc>
                <t>we</t>
                <t>often</t>
                <t>speak</t>
                <t>as</t>
                <t>if</t>
                <t>the</t>
                <t>most</t>
                <t>fashionable</t>
                <t>outfits</t>
                <t>are</t>
                <t>those</t>
                <t>that</t>
                <t>fully</t>
                <t>coordinate</t>
                <t>or</t>
                <punc>“</punc>
                <t>match</t>
                <punc>”</punc>
                <punc>[</punc>
                <t>10</t>
                <punc>]</punc>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>This</t>
                <t>suggests</t>
                <t>that</t>
                <t>pairing</t>
                <t>the</t>
                <t>same</t>
                <t>or</t>
                <t>similar</t>
                <t>colors</t>
                <t>with</t>
                <t>each</t>
                <t>other</t>
                <t>may</t>
                <t>be</t>
                <t>the</t>
                <t>key</t>
                <t>to</t>
                <t>fashion</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>On</t>
                <t>the</t>
                <t>other</t>
                <t>hand</t>
                <punc>,</punc>
                <t>fashion</t>
                <t>is</t>
                <t>often</t>
                <t>about</t>
                <t>being</t>
                <t>noticed</t>
                <punc>,</punc>
                <t>and</t>
                <t>so</t>
                <t>we</t>
                <t>might</t>
                <t>want</t>
                <t>color</t>
                <t>combinations</t>
                <t>that</t>
                <t>maximally</t>
                <t>differ</t>
                <t>from</t>
                <t>each</t>
                <t>other</t>
                <t>and</t>
                <punc>“</punc>
                <t>pop</t>
                <punc>”</punc>
                <punc>[</punc>
                <t>11</t>
                <punc>]</punc>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>Between</t>
                <t>these</t>
                <t>two</t>
                <t>extremes</t>
                <punc>,</punc>
                <t>the</t>
                <t>Goldilocks</t>
                <t>Principle</t>
                <t>suggests</t>
                <t>that</t>
                <t>the</t>
                <t>best</t>
                <t>color</t>
                <t>combinations</t>
                <t>are</t>
                <t>those</t>
                <t>that</t>
                <t>are</t>
                <t>neither</t>
                <t>too</t>
                <t>similar</t>
                <punc>(</punc>
                <punc>“</punc>
                <t>matchy</t>
                <punc>-</punc>
                <t>matchy</t>
                <punc>”</punc>
                <punc>)</punc>
                <t>nor</t>
                <t>too</t>
                <t>different</t>
                <punc>(</punc>
                <punc>“</punc>
                <t>clashing</t>
                <punc>”</punc>
                <punc>)</punc>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/4-annotate/in/other-connectors-3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Henry Cavendish (Extract)</title>
    <citation>Simple English Wikipedia: “Henry Cavendish”. Retrieved from https://simple.wikipedia.org/wiki/Henry_Cavendish on 20 Aug 2015.</citation>
    <url>https://simple.wikipedia.org/wiki/Henry_Cavendish</url>
    <info type="arise">
        <arise-info book="2"
                    section="2"
                    unit="3"
                    part="4"
                    item="2"
                    firstpage="23"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01">Henry</t>
                <t id="p01-s01-t02">Cavendish</t>
                <punc>(</punc>
                <t id="p01-s01-t03">1731</t>
                <punc>-</punc>
                <t id="p01-s01-t04">1810</t>
                <punc>)</punc>
                <t id="p01-s01-t05" type="GSL-1">was</t>
                <t id="p01-s01-t06" type="GSL-1">a</t>
                <t id="p01-s01-t07">British</t>
                <t id="p01-s01-t08" type="GSL-1">scientist</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s02">
                <anaphor>
                    <t id="p01-s02-t01" type="GSL-1">He</t>
                </anaphor>
                <t id="p01-s02-t02" type="GSL-1">is</t>
                <t id="p01-s02-t03" type="GSL-1">famous</t>
                <t id="p01-s02-t04" type="GSL-1">for</t>
                <t id="p01-s02-t05" type="GSL-1">discovering</t>
                <t id="p01-s02-t06">hydrogen</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s03">
                <t id="p01-s03-t01">Cavendish</t>
                <connector>
                    <t id="p01-s03-t02" type="GSL-1">also</t>
                </connector>
                <connector>
                    <t id="p01-s03-t03" type="GSL-1">claimed</t>
                    <t id="p01-s03-t04" type="GSL-1">that</t>
                </connector>
                <t id="p01-s03-t05" type="GSL-1">the</t>
                <t id="p01-s03-t06" type="GSL-1">force</t>
                <t id="p01-s03-t07" type="GSL-1">between</t>
                <t id="p01-s03-t08" type="GSL-1">the</t>
                <t id="p01-s03-t09" type="GSL-1">two</t>
                <t id="p01-s03-t10" type="GSL-2">electrical</t>
                <t id="p01-s03-t11" type="GSL-1">objects</t>
                <t id="p01-s03-t12" type="GSL-1">gets</t>
                <t id="p01-s03-t13" type="GSL-1">smaller</t>
                <t id="p01-s03-t14" type="GSL-1">as</t>
                <anaphor>
                    <t id="p01-s03-t15" type="GSL-1">they</t>
                </anaphor>
                <t id="p01-s03-t16" type="GSL-1">get</t>
                <t id="p01-s03-t17" type="GSL-1">further</t>
                <t id="p01-s03-t18" type="GSL-2">apart</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s04">
                <connector>
                    <t id="p01-s04-t01" type="GSL-1">If</t>
                </connector>
                <t id="p01-s04-t02" type="GSL-1">the</t>
                <t id="p01-s04-t03" type="GSL-1">distance</t>
                <t id="p01-s04-t04" type="GSL-1">between</t>
                <anaphor>
                    <t id="p01-s04-t05" type="GSL-1">them</t>
                </anaphor>
                <t id="p01-s04-t06" type="GSL-2">doubled</t>
                <punc>,</punc>
                <anaphor>
                    <t id="p01-s04-t07" type="GSL-1">the</t>
                    <t id="p01-s04-t08" type="GSL-1">force</t>
                </anaphor>
                <t id="p01-s04-t09" type="GSL-1">would</t>
                <t id="p01-s04-t10" type="GSL-1">be</t>
                <t id="p01-s04-t11" type="GSL-1">one</t>
                <t id="p01-s04-t12" type="GSL-1">quarter</t>
                <t id="p01-s04-t13" type="GSL-1">what</t>
                <anaphor>
                    <t id="p01-s04-t14" type="GSL-1">it</t>
                </anaphor>
                <t id="p01-s04-t15" type="GSL-1">was</t>
                <t id="p01-s04-t16" type="GSL-1">before</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s05">
                <anaphor>
                    <t id="p01-s05-t01" type="GSL-1">This</t>
                </anaphor>
                <t id="p01-s05-t02" type="GSL-1">was</t>
                <t id="p01-s05-t03" type="GSL-1">based</t>
                <t id="p01-s05-t04" type="GSL-1">on</t>
                <t id="p01-s05-t05" type="GSL-1">the</t>
                <t id="p01-s05-t06">inverse</t>
                <punc>-</punc>
                <t id="p01-s05-t07" type="GSL-1">square</t>
                <t id="p01-s05-t08" type="GSL-1">law</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/4-annotate/in/paraphrasing-and-quoting-3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>The Power of Kawaii: Viewing Cute Images Promotes a Careful Behavior and Narrows Attentional Focus (Extract)</title>
    <citation>Nittono H, Fukushima M, Yano A, Moriya H (2012) The Power of Kawaii: Viewing Cute Images Promotes a Careful Behavior and Narrows Attentional Focus. PLoS ONE 7(9): e46362. doi:10.1371/journal.pone.0046362</citation>
    <url>http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0046362</url>
    <info type="arise">
        <arise-info book="1"
                    section="3"
                    unit="5"
                    part="4"
                    item="1"
                    firstpage="47"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01" type="GSL-1">The</t>
                <t id="p01-s01-t02" type="Coxhead-AWL-2,AR-AWL-2b">participants</t>
                <t id="p01-s01-t03" type="GSL-1">were</t>
                <t id="p01-s01-t04" type="GSL-1">asked</t>
                <t id="p01-s01-t05" type="GSL-1">to</t>
                <t id="p01-s01-t06" type="GSL-2">perform</t>
                <t id="p01-s01-t07" type="GSL-1">a</t>
                <t id="p01-s01-t08" type="Coxhead-AWL-3,AR-AWL-3b">task</t>
                <t id="p01-s01-t09" type="Coxhead-AWL-1,AR-AWL-1b">requiring</t>
                <t id="p01-s01-t10" type="GSL-1">a</t>
                <t id="p01-s01-t11" type="GSL-1">high</t>
                <t id="p01-s01-t12" type="GSL-1">level</t>
                <t id="p01-s01-t13" type="GSL-1">of</t>
                <t id="p01-s01-t14" type="Coxhead-AWL-4,AR-AWL-4a">concentration</t>
                <t id="p01-s01-t15" type="GSL-1">twice</t>
                <punc>,</punc>
                <t id="p01-s01-t16" type="GSL-1">with</t>
                <t id="p01-s01-t17" type="GSL-1">a</t>
                <t id="p01-s01-t18" type="GSL-1">break</t>
                <t id="p01-s01-t19" type="GSL-1">of</t>
                <t id="p01-s01-t20" type="GSL-1">a</t>
                <t id="p01-s01-t21" type="GSL-1">few</t>
                <t id="p01-s01-t22" type="GSL-1">minutes</t>
                <t id="p01-s01-t23" type="GSL-1">between</t>
                <anaphor>
                    <t id="p01-s01-t24" type="GSL-1">the</t>
                    <t id="p01-s01-t25" type="Coxhead-AWL-3,AR-AWL-3b">tasks</t>
                </anaphor>
                <t id="p01-s01-t26" type="GSL-1">for</t>
                <t id="p01-s01-t27" type="Coxhead-AWL-5,AR-AWL-5b">mental</t>
                <t id="p01-s01-t28" type="Coxhead-AWL-6,AR-AWL-6b">recovery</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/2-attach-ids/out/other-connectors-3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Henry Cavendish (Extract)</title>
    <citation>Simple English Wikipedia: “Henry Cavendish”. Retrieved from https://simple.wikipedia.org/wiki/Henry_Cavendish on 20 Aug 2015.</citation>
    <url>https://simple.wikipedia.org/wiki/Henry_Cavendish</url>
    <info type="arise">
        <arise-info book="2"
                    section="2"
                    unit="3"
                    part="4"
                    item="2"
                    firstpage="23"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01">Henry</t>
                <t id="p01-s01-t02">Cavendish</t>
                <punc>(</punc>
                <t id="p01-s01-t03">1731</t>
                <punc>-</punc>
                <t id="p01-s01-t04">1810</t>
                <punc>)</punc>
                <t id="p01-s01-t05">was</t>
                <t id="p01-s01-t06">a</t>
                <t id="p01-s01-t07">British</t>
                <t id="p01-s01-t08">scientist</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s02">
                <t id="p01-s02-t01">He</t>
                <t id="p01-s02-t02">is</t>
                <t id="p01-s02-t03">famous</t>
                <t id="p01-s02-t04">for</t>
                <t id="p01-s02-t05">discovering</t>
                <t id="p01-s02-t06">hydrogen</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s03">
                <t id="p01-s03-t01">Cavendish</t>
                <t id="p01-s03-t02">also</t>
                <t id="p01-s03-t03">claimed</t>
                <t id="p01-s03-t04">that</t>
                <t id="p01-s03-t05">the</t>
                <t id="p01-s03-t06">force</t>
                <t id="p01-s03-t07">between</t>
                <t id="p01-s03-t08">the</t>
                <t id="p01-s03-t09">two</t>
                <t id="p01-s03-t10">electrical</t>
                <t id="p01-s03-t11">objects</t>
                <t id="p01-s03-t12">gets</t>
                <t id="p01-s03-t13">smaller</t>
                <t id="p01-s03-t14">as</t>
                <t id="p01-s03-t15">they</t>
                <t id="p01-s03-t16">get</t>
                <t id="p01-s03-t17">further</t>
                <t id="p01-s03-t18">apart</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s04">
                <t id="p01-s04-t01">If</t>
                <t id="p01-s04-t02">the</t>
                <t id="p01-s04-t03">distance</t>
                <t id="p01-s04-t04">between</t>
                <t id="p01-s04-t05">them</t>
                <t id="p01-s04-t06">doubled</t>
                <punc>,</punc>
                <t id="p01-s04-t07">the</t>
                <t id="p01-s04-t08">force</t>
                <t id="p01-s04-t09">would</t>
                <t id="p01-s04-t10">be</t>
                <t id="p01-s04-t11">one</t>
                <t id="p01-s04-t12">quarter</t>
                <t id="p01-s04-t13">what</t>
                <t id="p01-s04-t14">it</t>
                <t id="p01-s04-t15">was</t>
                <t id="p01-s04-t16">before</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s05">
                <t id="p01-s05-t01">This</t>
                <t id="p01-s05-t02">was</t>
                <t id="p01-s05-t03">based</t>
                <t id="p01-s05-t04">on</t>
                <t id="p01-s05-t05">the</t>
                <t id="p01-s05-t06">inverse</t>
                <punc>-</punc>
                <t id="p01-s05-t07">square</t>
                <t id="p01-s05-t08">law</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>
