=== fildpauz/adaps/docs/xml/adaps.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/adaps.dtd.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE document SYSTEM "adaps.dtd.dtd">

    <document>
    ...
    </document>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT document (title,citation,url,info?,body)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT citation (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT url (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT info (arise-info)?>
<!ATTLIST info
    type (arise|science-news|other) #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT arise-info EMPTY>
<!ATTLIST arise-info
    book CDATA #REQUIRED
    section CDATA #IMPLIED
    unit CDATA #IMPLIED
    part CDATA #IMPLIED
    item CDATA #IMPLIED
    firstpage CDATA #REQUIRED
    lastpage CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT body (paragraph)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT paragraph (sentence)*>
<!ATTLIST paragraph
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sentence (t|punc|abbr|anaphor|emph|connector|sentence|term)*>
<!ATTLIST sentence
    par-function CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT t (#PCDATA)>
<!ATTLIST t
    id CDATA #IMPLIED
    type CDATA #IMPLIED
    parts CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT punc (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT abbr (t)*>
<!ATTLIST abbr
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT anaphor (t|punc)*>
<!ATTLIST anaphor
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT emph (t|punc|abbr|anaphor|term)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT connector (t|anaphor)*>
<!ATTLIST connector
    id CDATA #IMPLIED
    type CDATA #IMPLIED
    info CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT term (t|punc)*>
<!ATTLIST term
    id CDATA #IMPLIED
    info CDATA #IMPLIED
  >

=== fildpauz/adaps/docs/pipeline/2-attach-ids/out/paragraphs-5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Facebook Use Predicts Declines in Subjective Well-Being in Young Adults (Extract 1)</title>
    <citation>Kross E, Verduyn P, Demiralp E, Park J, Lee DS, et al., (2013), Facebook Use Predicts Declines in Subjective Well-Being in Young Adults., PLoS ONE 8(8): e69841., doi:10.1371/journal.pone.0069841</citation>
    <url>doi:10.1371/journal.pone.0069841</url>
    <info type="arise">
        <arise-info book="1"
                    section="2"
                    unit="6"
                    part="2"
                    item="E"
                    firstpage="28"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence id="p01-s01">
                <t id="p01-s01-t01">Within</t>
                <t id="p01-s01-t02">a</t>
                <t id="p01-s01-t03">relatively</t>
                <t id="p01-s01-t04">short</t>
                <t id="p01-s01-t05">timespan</t>
                <punc>,</punc>
                <t id="p01-s01-t06">Facebook</t>
                <t id="p01-s01-t07">has</t>
                <t id="p01-s01-t08">revolutionized</t>
                <t id="p01-s01-t09">the</t>
                <t id="p01-s01-t10">way</t>
                <t id="p01-s01-t11">people</t>
                <t id="p01-s01-t12">interact</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s02">
                <t id="p01-s02-t01">Yet</t>
                <punc>,</punc>
                <t id="p01-s02-t02">whether</t>
                <t id="p01-s02-t03">using</t>
                <t id="p01-s02-t04">Facebook</t>
                <t id="p01-s02-t05">predicts</t>
                <t id="p01-s02-t06">changes</t>
                <t id="p01-s02-t07">in</t>
                <t id="p01-s02-t08">subjective</t>
                <t id="p01-s02-t09">well-being</t>
                <t id="p01-s02-t10">over</t>
                <t id="p01-s02-t11">time</t>
                <t id="p01-s02-t12">is</t>
                <t id="p01-s02-t13">unknown</t>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s03">
                <t id="p01-s03-t01">We</t>
                <t id="p01-s03-t02">addressed</t>
                <t id="p01-s03-t03">this</t>
                <t id="p01-s03-t04">issue</t>
                <t id="p01-s03-t05">by</t>
                <t id="p01-s03-t06">performing</t>
                <t id="p01-s03-t07">lagged</t>
                <t id="p01-s03-t08">analyses</t>
                <t id="p01-s03-t09">on</t>
                <t id="p01-s03-t10">experience</t>
                <t id="p01-s03-t11">sampled</t>
                <t id="p01-s03-t12">data</t>
                <punc>,</punc>
                <t id="p01-s03-t13">an</t>
                <t id="p01-s03-t14">approach</t>
                <t id="p01-s03-t15">that</t>
                <t id="p01-s03-t16">allowed</t>
                <t id="p01-s03-t17">us</t>
                <t id="p01-s03-t18">to</t>
                <t id="p01-s03-t19">take</t>
                <t id="p01-s03-t20">advantage</t>
                <t id="p01-s03-t21">of</t>
                <t id="p01-s03-t22">the</t>
                <t id="p01-s03-t23">relative</t>
                <t id="p01-s03-t24">timing</t>
                <t id="p01-s03-t25">of</t>
                <t id="p01-s03-t26">participants'</t>
                <t id="p01-s03-t27">naturally</t>
                <t id="p01-s03-t28">occurring</t>
                <t id="p01-s03-t29">behaviors</t>
                <t id="p01-s03-t30">and</t>
                <t id="p01-s03-t31">psychological</t>
                <t id="p01-s03-t32">states</t>
                <t id="p01-s03-t33">to</t>
                <t id="p01-s03-t34">draw</t>
                <t id="p01-s03-t35">inferences</t>
                <t id="p01-s03-t36">about</t>
                <t id="p01-s03-t37">their</t>
                <t id="p01-s03-t38">likely</t>
                <t id="p01-s03-t39">causal</t>
                <t id="p01-s03-t40">sequence</t>
                <punc>[</punc>
                <t id="p01-s03-t41">17</t>
                <punc>]</punc>
                <punc>,</punc>
                <punc>[</punc>
                <t id="p01-s03-t42">18</t>
                <punc>]</punc>
                <punc>.</punc>
            </sentence>
            <sentence id="p01-s04">
                <t id="p01-s04-t01">These</t>
                <t id="p01-s04-t02">analyses</t>
                <t id="p01-s04-t03">indicated</t>
                <t id="p01-s04-t04">that</t>
                <t id="p01-s04-t05">Facebook</t>
                <t id="p01-s04-t06">use</t>
                <t id="p01-s04-t07">predicts</t>
                <t id="p01-s04-t08">declines</t>
                <t id="p01-s04-t09">in</t>
                <t id="p01-s04-t10">the</t>
                <t id="p01-s04-t11">two</t>
                <t id="p01-s04-t12">components</t>
                <t id="p01-s04-t13">of</t>
                <t id="p01-s04-t14">subjective</t>
                <t id="p01-s04-t15">well-being</t>
                <punc>:</punc>
                <t id="p01-s04-t16">how</t>
                <t id="p01-s04-t17">people</t>
                <t id="p01-s04-t18">feel</t>
                <t id="p01-s04-t19">moment</t>
                <t id="p01-s04-t20">to</t>
                <t id="p01-s04-t21">moment</t>
                <t id="p01-s04-t22">and</t>
                <t id="p01-s04-t23">how</t>
                <t id="p01-s04-t24">satisfied</t>
                <t id="p01-s04-t25">they</t>
                <t id="p01-s04-t26">are</t>
                <t id="p01-s04-t27">with</t>
                <t id="p01-s04-t28">their</t>
                <t id="p01-s04-t29">lives</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/1-tokenize/out/language-learning-subj.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../../../xml/adaps.dtd">
<document>
<title>Extract from If at First You Don’t Succeed, Sit Back and Listen</title>
<citation>Wallace, S (2014) If at First You Don’t Succeed, Sit Back and Listen. EveryONE (PLoS One blog).
Retrieved from http:// blogs.plos.org/everyone/2014/07/22/first-dont-succeed-sit-back-listen/ on 20 August 2015.</citation>
<url>http:// blogs.plos.org/everyone/2014/07/22/first-dont-succeed-sit-back-listen/</url>
<body>
<paragraph>
<sentence>
<t>Few</t>
<t>of</t>
<t>us</t>
<t>remember</t>
<t>how</t>
<t>easily</t>
<t>we</t>
<t>learned</t>
<t>language</t>
<t>as</t>
<t>children</t>
<punc>.</punc>
</sentence>
<sentence>
<t>Although</t>
<t>the</t>
<t>acquisition</t>
<t>wasn’t</t>
<t>always</t>
<t>graceful</t>
<t>then—‘awry’</t>
<t>never</t>
<t>sounds</t>
<t>the</t>
<t>same</t>
<t>way</t>
<t>aloud</t>
<t>as</t>
<t>the</t>
<t>way</t>
<t>I</t>
<t>read</t>
<t>it</t>
<t>in</t>
<t>my</t>
<t>head—</t>
<t>using</t>
<t>our</t>
<t>primary</t>
<t>language</t>
<t>as</t>
<t>an</t>
<t>adult</t>
<t>is</t>
<t>as</t>
<t>habitual</t>
<t>as</t>
<t>tying</t>
<t>shoelaces</t>
<t>and</t>
<t>seemingly</t>
<t>as</t>
<t>instinctual</t>
<t>as</t>
<t>smiling</t>
<punc>.</punc>
</sentence>
<sentence>
<t>Given</t>
<t>how</t>
<t>involuntarily</t>
<t>we</t>
<t>adults</t>
<t>use</t>
<t>our</t>
<t>primary</t>
<t>language</t>
<punc>,</punc>
<t>it’s</t>
<t>shocking</t>
<t>how</t>
<t>difficult</t>
<t>learning</t>
<t>new</t>
<t>languages</t>
<t>as</t>
<t>an</t>
<t>adult</t>
<t>can</t>
<t>be</t>
<punc>.</punc>
</sentence>
<sentence>
<t>The</t>
<t>authors</t>
<t>of</t>
<t>a</t>
<t>recent</t>
<t>PLOS</t>
<t>ONE</t>
<t>paper</t>
<t>postulated</t>
<t>that</t>
<t>the</t>
<t>very</t>
<t>functions</t>
<t>we</t>
<t>develop</t>
<t>as</t>
<t>our</t>
<t>brains</t>
<t>mature</t>
<t>as</t>
<t>adults</t>
<t>may</t>
<t>be</t>
<t>what</t>
<t>hinder</t>
<t>us</t>
<t>from</t>
<t>mastering</t>
<t>language</t>
<t>the</t>
<t>way</t>
<t>a</t>
<t>child</t>
<t>does</t>
<punc>.</punc>
</sentence>
<sentence>
<t>We</t>
<t>might</t>
<punc>,</punc>
<t>in</t>
<t>fact</t>
<punc>,</punc>
<t>be</t>
<punc>“</punc>
<t>trying</t>
<punc>”</punc>
<t>too</t>
<t>hard</t>
<punc>.</punc>
</sentence>
</paragraph>
<paragraph>
<sentence>
<t>Researchers</t>
<t>have</t>
<t>shown</t>
<t>in</t>
<t>previous</t>
<t>studies</t>
<t>that</t>
<t>adults</t>
<t>outperform</t>
<t>children</t>
<t>in</t>
<t>tasks</t>
<t>that</t>
<t>require</t>
<t>attentional</t>
<t>focus</t>
<t>and</t>
<t>effort</t>
<punc>.</punc>
</sentence>
<sentence>
<t>This</t>
<t>is</t>
<t>because</t>
<t>the</t>
<t>regions</t>
<t>of</t>
<t>the</t>
<t>brain</t>
<t>associated</t>
<t>with</t>
<t>these</t>
<t>abilities—the</t>
<t>prefrontal</t>
<t>and</t>
<t>parietal</t>
<t>cortices—develop</t>
<t>more</t>
<t>slowly</t>
<punc>,</punc>
<t>and</t>
<t>as</t>
<t>a</t>
<t>result</t>
<punc>,</punc>
<t>these</t>
<t>abilities</t>
<t>become</t>
<t>stronger</t>
<t>as</t>
<t>we</t>
<t>age</t>
<punc>.</punc>
</sentence>
<sentence>
<t>In</t>
<t>other</t>
<t>words</t>
<punc>,</punc>
<t>adult</t>
<t>brains</t>
<t>develop</t>
<t>abilities</t>
<t>that</t>
<t>help</t>
<t>us</t>
<punc>“</punc>
<t>try</t>
<t>harder</t>
<punc>.</punc>
<punc>”</punc>
</sentence>
<sentence>
<t>These</t>
<t>same</t>
<t>capabilities</t>
<t>may</t>
<punc>,</punc>
<t>however</t>
<punc>,</punc>
<t>interfere</t>
<t>with</t>
<t>our</t>
<t>capacity</t>
<t>to</t>
<t>learn</t>
<t>some</t>
<t>aspects</t>
<t>of</t>
<t>language</t>
<t>as</t>
<t>adults</t>
<punc>,</punc>
<t>like</t>
<t>the</t>
<t>tricky</t>
<t>networks</t>
<t>that</t>
<t>underlie</t>
<t>grammar</t>
<punc>.</punc>
</sentence>
</paragraph>
</body>
</document>

=== fildpauz/adaps/docs/pipeline/2-attach-ids/in/augmented-reality.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document
  SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Augmented reality (Extract)</title>
    <citation>Wikipedia contributors, "Augmented reality," Wikipedia, The Free Encyclopedia, https://en.wikipedia.org/w/index.php?title=Augmented_reality&amp;oldid=758501273 (accessed January 25, 2017).</citation>
    <url>https://en.wikipedia.org/w/index.php?title=Augmented_reality&amp;oldid=758501273</url>
    <info type="wikipedia"/>
    <body>
        <paragraph>
            <sentence>
                <t>Augmented</t>
                <t>reality</t>
                <punc>(</punc>
                <t>AR</t>
                <punc>)</punc>
                <t>is</t>
                <t>a</t>
                <t>live</t>
                <t>direct</t>
                <t>or</t>
                <t>indirect</t>
                <t>view</t>
                <t>of</t>
                <t>a</t>
                <t>physical</t>
                <punc>,</punc>
                <t>real</t>
                <punc>-</punc>
                <t>world</t>
                <t>environment</t>
                <t>whose</t>
                <t>elements</t>
                <t>are</t>
                <t>augmented</t>
                <punc>(</punc>
                <t>or</t>
                <t>supplemented</t>
                <punc>)</punc>
                <t>by</t>
                <t>computer</t>
                <punc>-</punc>
                <t>generated</t>
                <t>sensory</t>
                <t>input</t>
                <t>such</t>
                <t>as</t>
                <t>sound</t>
                <punc>,</punc>
                <t>video</t>
                <punc>,</punc>
                <t>graphics</t>
                <t>or</t>
                <t>GPS</t>
                <t>data</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>It</t>
                <t>is</t>
                <t>related</t>
                <t>to</t>
                <t>a</t>
                <t>more</t>
                <t>general</t>
                <t>concept</t>
                <t>called</t>
                <t>mediated</t>
                <t>reality</t>
                <punc>,</punc>
                <t>in</t>
                <t>which</t>
                <t>a</t>
                <t>view</t>
                <t>of</t>
                <t>reality</t>
                <t>is</t>
                <t>modified</t>
                <punc>(</punc>
                <t>possibly</t>
                <t>even</t>
                <t>diminished</t>
                <t>rather</t>
                <t>than</t>
                <t>augmented</t>
                <punc>)</punc>
                <t>by</t>
                <t>a</t>
                <t>computer</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>As</t>
                <t>a</t>
                <t>result</t>
                <punc>,</punc>
                <t>the</t>
                <t>technology</t>
                <t>functions</t>
                <t>by</t>
                <t>enhancing</t>
                <t>one's</t>
                <t>current</t>
                <t>perception</t>
                <t>of</t>
                <t>reality</t>
                <punc>.</punc>
                <t>[1]</t>
            </sentence>
            <sentence>
                <t>By</t>
                <t>contrast</t>
                <punc>,</punc>
                <t>virtual</t>
                <t>reality</t>
                <t>replaces</t>
                <t>the</t>
                <t>real</t>
                <t>world</t>
                <t>with</t>
                <t>a</t>
                <t>simulated</t>
                <t>one</t>
                <punc>.</punc>
                <t>[2][3]</t>
            </sentence>
            <sentence>
                <t>Augmentation</t>
                <t>is</t>
                <t>conventionally</t>
                <t>in</t>
                <t>real</t>
                <t>time</t>
                <t>and</t>
                <t>in</t>
                <t>semantic</t>
                <t>context</t>
                <t>with</t>
                <t>environmental</t>
                <t>elements</t>
                <punc>,</punc>
                <t>such</t>
                <t>as</t>
                <t>sports</t>
                <t>scores</t>
                <t>on</t>
                <t>TV</t>
                <t>during</t>
                <t>a</t>
                <t>match</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>With</t>
                <t>the</t>
                <t>help</t>
                <t>of</t>
                <t>advanced</t>
                <t>AR</t>
                <t>technology</t>
                <punc>(</punc>
                <t>e.g.</t>
                <t>adding</t>
                <t>computer</t>
                <t>vision</t>
                <t>and</t>
                <t>object</t>
                <t>recognition</t>
                <punc>)</punc>
                <t>the</t>
                <t>information</t>
                <t>about</t>
                <t>the</t>
                <t>surrounding</t>
                <t>real</t>
                <t>world</t>
                <t>of</t>
                <t>the</t>
                <t>user</t>
                <t>becomes</t>
                <t>interactive</t>
                <t>and</t>
                <t>digitally</t>
                <t>manipulable</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>Information</t>
                <t>about</t>
                <t>the</t>
                <t>environment</t>
                <t>and</t>
                <t>its</t>
                <t>objects</t>
                <t>is</t>
                <t>overlaid</t>
                <t>on</t>
                <t>the</t>
                <t>real</t>
                <t>world</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>This</t>
                <t>information</t>
                <t>can</t>
                <t>be</t>
                <t>virtual</t>
                <t>[4][5][6][7][8]</t>
                <t>or</t>
                <t>real</t>
                <punc>,</punc>
                <t>e.g.</t>
                <t>seeing</t>
                <t>other</t>
                <t>real</t>
                <t>sensed</t>
                <t>or</t>
                <t>measured</t>
                <t>information</t>
                <t>such</t>
                <t>as</t>
                <t>electromagnetic</t>
                <t>radio</t>
                <t>waves</t>
                <t>overlaid</t>
                <t>in</t>
                <t>exact</t>
                <t>alignment</t>
                <t>with</t>
                <t>where</t>
                <t>they</t>
                <t>actually</t>
                <t>are</t>
                <t>in</t>
                <t>space</t>
                <punc>.</punc>
                <t>[9][10]</t>
            </sentence>
            <sentence>
                <t>Augmented</t>
                <t>reality</t>
                <t>brings</t>
                <t>out</t>
                <t>the</t>
                <t>components</t>
                <t>of</t>
                <t>the</t>
                <t>digital</t>
                <t>world</t>
                <t>into</t>
                <t>a</t>
                <t>person's</t>
                <t>perceived</t>
                <t>real</t>
                <t>world</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>One</t>
                <t>example</t>
                <t>is</t>
                <t>an</t>
                <t>AR</t>
                <t>Helmet</t>
                <t>for</t>
                <t>construction</t>
                <t>workers</t>
                <t>which</t>
                <t>displays</t>
                <t>information</t>
                <t>about</t>
                <t>the</t>
                <t>construction</t>
                <t>sites</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/2-attach-ids/in/paragraphs-5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Facebook Use Predicts Declines in Subjective Well-Being in Young Adults (Extract 1)</title>
    <citation>Kross E, Verduyn P, Demiralp E, Park J, Lee DS, et al., (2013), Facebook Use Predicts Declines in Subjective Well-Being in Young Adults., PLoS ONE 8(8): e69841., doi:10.1371/journal.pone.0069841</citation>
    <url>doi:10.1371/journal.pone.0069841</url>
    <info type="arise">
        <arise-info book="1" section="2" unit="6" part="2" item="E" firstpage="28"/>
    </info>
    <body>
        <paragraph>
            <sentence>
                <t>Within</t>
                <t>a</t>
                <t>relatively</t>
                <t>short</t>
                <t>timespan</t>
                <punc>,</punc>
                <t>Facebook</t>
                <t>has</t>
                <t>revolutionized</t>
                <t>the</t>
                <t>way</t>
                <t>people</t>
                <t>interact</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>Yet</t>
                <punc>,</punc>
                <t>whether</t>
                <t>using</t>
                <t>Facebook</t>
                <t>predicts</t>
                <t>changes</t>
                <t>in</t>
                <t>subjective</t>
                <t>well-being</t>
                <t>over</t>
                <t>time</t>
                <t>is</t>
                <t>unknown</t>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>We</t>
                <t>addressed</t>
                <t>this</t>
                <t>issue</t>
                <t>by</t>
                <t>performing</t>
                <t>lagged</t>
                <t>analyses</t>
                <t>on</t>
                <t>experience</t>
                <t>sampled</t>
                <t>data</t>
                <punc>,</punc>
                <t>an</t>
                <t>approach</t>
                <t>that</t>
                <t>allowed</t>
                <t>us</t>
                <t>to</t>
                <t>take</t>
                <t>advantage</t>
                <t>of</t>
                <t>the</t>
                <t>relative</t>
                <t>timing</t>
                <t>of</t>
                <t>participants'</t>
                <t>naturally</t>
                <t>occurring</t>
                <t>behaviors</t>
                <t>and</t>
                <t>psychological</t>
                <t>states</t>
                <t>to</t>
                <t>draw</t>
                <t>inferences</t>
                <t>about</t>
                <t>their</t>
                <t>likely</t>
                <t>causal</t>
                <t>sequence</t>
                <punc>[</punc>
                <t>17</t>
                <punc>]</punc>
                <punc>,</punc>
                <punc>[</punc>
                <t>18</t>
                <punc>]</punc>
                <punc>.</punc>
            </sentence>
            <sentence>
                <t>These</t>
                <t>analyses</t>
                <t>indicated</t>
                <t>that</t>
                <t>Facebook</t>
                <t>use</t>
                <t>predicts</t>
                <t>declines</t>
                <t>in</t>
                <t>the</t>
                <t>two</t>
                <t>components</t>
                <t>of</t>
                <t>subjective</t>
                <t>well-being</t>
                <punc>:</punc>
                <t>how</t>
                <t>people</t>
                <t>feel</t>
                <t>moment</t>
                <t>to</t>
                <t>moment</t>
                <t>and</t>
                <t>how</t>
                <t>satisfied</t>
                <t>they</t>
                <t>are</t>
                <t>with</t>
                <t>their</t>
                <t>lives</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>

=== fildpauz/adaps/docs/pipeline/4-annotate/out/resemblance-connectors-9.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../../../xml/adaps.dtd">
<document>
    <title>Nucleon (Extract)</title>
    <citation>Simple English Wikipedia: “Nucleon”. Retrieved from https://simple.wikipedia.org/wiki/Nucleon on 20 Aug 2015.</citation>
    <url>https://simple.wikipedia.org/wiki/Nucleon</url>
    <info type="arise">
        <arise-info book="2" section="2" unit="1" part="4" item="8" firstpage="16"/>
    </info>
    <body>
        <paragraph id="p01">
            <sentence par-function="topic|supporting|concluding" id="p01-s01">
                <t id="p01-s01-t01" type="GSL-1">In</t>
                <t id="p01-s01-t02">physics</t>
                <t id="p01-s01-t03" type="GSL-1">and</t>
                <t id="p01-s01-t04">chemistry</t>
                <punc>,</punc>
                <term id="p01-s01-e01" info="">
                    <t id="p01-s01-t05" type="GSL-1">a</t>
                    <t id="p01-s01-t06">nucleon</t>
                </term>
                <t id="p01-s01-t07" type="GSL-2">refers</t>
                <t id="p01-s01-t08" type="GSL-1">to</t>
                <t id="p01-s01-t09" type="GSL-1">any</t>
                <t id="p01-s01-t10">subatomic</t>
                <t id="p01-s01-t11" type="GSL-1">particle</t>
                <t id="p01-s01-t12" type="Coxhead-AWL-9,AR-AWL-9a">found</t>
                <t id="p01-s01-t13" type="GSL-1">in</t>
                <t id="p01-s01-t14" type="GSL-1">the</t>
                <t id="p01-s01-t15">nucleus</t>
                <t id="p01-s01-t16" type="GSL-1">of</t>
                <t id="p01-s01-t17" type="GSL-1">an</t>
                <t id="p01-s01-t18">atom</t>
                <punc>.</punc>
            </sentence>
            <sentence par-function="topic|supporting|concluding" id="p01-s02">
                <connector id="p01-s02-c01" type="" info="">
                    <t id="p01-s02-t01" type="GSL-1">For</t>
                    <t id="p01-s02-t02" type="Coxhead-AWL-3,AR-AWL-3a">instance</t>
                </connector>
                <punc>,</punc>
                <t id="p01-s02-t03">protons</t>
                <t id="p01-s02-t04" type="GSL-1">and</t>
                <t id="p01-s02-t05">neutrons</t>
                <t id="p01-s02-t06" type="GSL-1">are</t>
                <t id="p01-s02-t07">nucleons</t>
                <punc>,</punc>
                <connector id="p01-s02-c02" type="" info="">
                    <t id="p01-s02-t08" type="GSL-1">since</t>
                </connector>
                <anaphor id="p01-s02-a01" info="">
                    <t id="p01-s02-t09" type="GSL-1">they</t>
                </anaphor>
                <t id="p01-s02-t10" type="GSL-1">are</t>
                <t id="p01-s02-t11" type="GSL-1">in</t>
                <t id="p01-s02-t12" type="GSL-1">the</t>
                <t id="p01-s02-t13">nucleus</t>
                <t id="p01-s02-t14" type="GSL-1">of</t>
                <anaphor id="p01-s02-a02" info="">
                    <t id="p01-s02-t15" type="GSL-1">the</t>
                    <t id="p01-s02-t16">atom</t>
                </anaphor>
                <punc>.</punc>
            </sentence>
            <sentence par-function="topic|supporting|concluding" id="p01-s03">
                <t id="p01-s03-t01">Quarks</t>
                <t id="p01-s03-t02" type="GSL-1">are</t>
                <t id="p01-s03-t03" type="GSL-1">also</t>
                <t id="p01-s03-t04">nucleons</t>
                <connector id="p01-s03-c01" type="" info="">
                    <t id="p01-s03-t05" type="GSL-1">if</t>
                </connector>
                <anaphor id="p01-s03-a01" info="">
                    <t id="p01-s03-t06" type="GSL-1">they</t>
                </anaphor>
                <t id="p01-s03-t07" type="GSL-1">are</t>
                <t id="p01-s03-t08" type="Coxhead-AWL-9,AR-AWL-9a">found</t>
                <t id="p01-s03-t09" type="GSL-2">inside</t>
                <t id="p01-s03-t10" type="GSL-1">a</t>
                <t id="p01-s03-t11">proton</t>
                <t id="p01-s03-t12" type="GSL-1">or</t>
                <t id="p01-s03-t13">neutron</t>
                <punc>.</punc>
            </sentence>
        </paragraph>
    </body>
</document>
